"""empty message

Revision ID: 81d6c55ec553
Revises: 5bcd939f05a1
Create Date: 2026-01-09 15:24:05.914154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d6c55ec553'
down_revision = '5bcd939f05a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('planetid', sa.Integer(), nullable=False),
    sa.Column('peopleid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['peopleid'], ['people.id'], ),
    sa.ForeignKeyConstraint(['planetid'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
